---
- name: Configure opencanary
  copy:
    content: "{{ __opencanary_config }}"
    dest: "{{ opencanary_path }}/opencanary.conf"
  notify: restart opencanary

- name: Configure opencanary log rotation
  template:
    src: logrotate.conf.j2
    dest: "{{ opencanary_logrotate_path }}/opencanary"

- name: Configure systemd
  template:
    src: opencanary.service.j2
    dest: "{{ opencanary_systemd_path }}/opencanary.service"
