---
- include_tasks: variables.yml
- include_tasks: "setup-{{ ansible_os_family }}.yml"
- include_tasks: setup.yml
- include_tasks: configure.yml

# finalize
- name: Mark opencanary enabled on boot, and state if set
  systemd:
    name: opencanary
    state: "{{ opencanary_service_state }}"
    enabled: true
    daemon_reload: true
