---
- name: Converge
  hosts: all
  vars:
    opencanary_loggers:
      file: /tmp/opencanary.log
      console: ext://sys.stdout
    opencanary_config:
      device.node_id: molecule-docker
      rdp.enabled: true
  tasks:
    - name: Include opencanary
      include_role:
        name: opencanary
